: ${BUILD_TYPE:="Release"}

: ${CAFFE_BUILD_TYPE:=$BUILD_TYPE}
: ${CAFFE_SSD_BUILD_TYPE:=$BUILD_TYPE}

: ${PYTORCH_BUILD_TYPE:=$BUILD_TYPE}
: ${TORCHVISION_BUILD_TYPE:=$BUILD_TYPE}
: ${DETECTRON2_BUILD_TYPE:=$BUILD_TYPE}
: ${MMCV_BUILD_TYPE:=$BUILD_TYPE}

: ${TENSORFLOW_BUILD_TYPE:=$BUILD_TYPE}
