: ${BUILD_TYPE:="Release"}

: ${CAFFE_BUILD_TYPE=$BUILD_TYPE}
: ${CAFFE_SSD_BUILD_TYPE=$BUILD_TYPE}

: ${CAFFE2_BUILD_TYPE=$BUILD_TYPE}

: ${MXNET_BUILD_TYPE=$BUILD_TYPE}

: ${PYTORCH_BUILD_TYPE=$BUILD_TYPE}

: ${TENSORFLOW_BUILD_TYPE=$BUILD_TYPE}
