#!/bin/bash

# Caffe

: ${CAFFE_CHECKOUT_TARGET:=$CAFFE_VERSION}
: ${CAFFE_SSD_CHECKOUT_TARGET:=$CAFFE_SSD_VERSION}

# Caffe2

: ${CAFFE2_CHECKOUT_TARGET:=v$CAFFE2_VERSION}
: ${DETECTRON_CHECKOUT_TARGET:=$DETECTRON_VERSION}

# MXNet

: ${MXNET_CHECKOUT_TARGET:=$MXNET_VERSION}
: ${GLUONCV_CHECKOUT_TARGET:=v$GLUONCV_VERSION}

# Pytorch

: ${PYTORCH_CHECKOUT_TARGET:=v$PYTORCH_VERSION}
: ${APEX_CHECKOUT_TARGET:=$APEX_VERSION}
: ${FVCORE_CHECKOUT_TARGET:=$FVCORE_VERSION}
: ${DETECTRON2_CHECKOUT_TARGET:=v$DETECTRON2_VERSION}
: ${TORCHVISION_CHECKOUT_TARGET:=v$TORCHVISION_VERSION}

# Tensorflow

: ${TENSORFLOW_CHECKOUT_TARGET:=r$TENSORFLOW_VERSION}

: ${TF_OD_API_CHECKOUT_TARGET:=$TF_OD_API_VERSION}
