#!/bin/bash

# Caffe

: ${CAFFE_CHECKOUT_TARGET:=$CAFFE_VERSION}
: ${CAFFE_SSD_CHECKOUT_TARGET:=$CAFFE_SSD_VERSION}

# MXNet

: ${MXNET_CHECKOUT_TARGET:=$MXNET_VERSION}
: ${GLUONCV_CHECKOUT_TARGET:=v$GLUONCV_VERSION}

# Pytorch

: ${PYTORCH_CHECKOUT_TARGET:=v$PYTORCH_VERSION}
: ${FVCORE_CHECKOUT_TARGET:=$FVCORE_VERSION}
: ${DETECTRON2_CHECKOUT_TARGET:=v$DETECTRON2_VERSION}
: ${TORCHVISION_CHECKOUT_TARGET:=v$TORCHVISION_VERSION}
: ${CLASSYVISION_CHECKOUT_TARGET:=v$CLASSYVISION_VERSION}

# Tensorflow

: ${TENSORFLOW_CHECKOUT_TARGET:=v$TENSORFLOW_VERSION}
